/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package baitapthuhanh4;

/**
 *
 * @author Admin
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ibHienThi = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Button7 = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        ButtonChia = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        ButtonNhan = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        ButtonTru = new javax.swing.JButton();
        ButtonC = new javax.swing.JButton();
        Button0 = new javax.swing.JButton();
        ButtonBang = new javax.swing.JButton();
        ButtonCong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ibHienThi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ibHienThi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ibHienThi.setText("0");
        ibHienThi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel1.setLayout(new java.awt.GridLayout(4, 4, 2, 2));

        Button7.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        Button7.setText("7");
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });
        jPanel1.add(Button7);

        Button8.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        Button8.setText("8");
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });
        jPanel1.add(Button8);

        Button9.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        Button9.setText("9");
        Button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9ActionPerformed(evt);
            }
        });
        jPanel1.add(Button9);

        ButtonChia.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        ButtonChia.setText("/");
        ButtonChia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonChiaActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonChia);

        Button4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        Button4.setText("4");
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });
        jPanel1.add(Button4);

        Button5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        Button5.setText("5");
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });
        jPanel1.add(Button5);

        Button6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        Button6.setText("6");
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });
        jPanel1.add(Button6);

        ButtonNhan.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        ButtonNhan.setText("X");
        ButtonNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNhanActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonNhan);

        Button1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        Button1.setText("1");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });
        jPanel1.add(Button1);

        Button2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        Button2.setText("2");
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });
        jPanel1.add(Button2);

        Button3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        Button3.setText("3");
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });
        jPanel1.add(Button3);

        ButtonTru.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        ButtonTru.setText("-");
        ButtonTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTruActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonTru);

        ButtonC.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        ButtonC.setText("C");
        ButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonC);

        Button0.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        Button0.setText("0");
        Button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button0ActionPerformed(evt);
            }
        });
        jPanel1.add(Button0);

        ButtonBang.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        ButtonBang.setText("=");
        ButtonBang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBangActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonBang);

        ButtonCong.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        ButtonCong.setText("+");
        ButtonCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCongActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonCong);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(ibHienThi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ibHienThi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
        String gt = this.ibHienThi.getText();
        if (gt.length() < 10)
        {
            if (gt.equals("0")){
                gt = "";
            }
            this.ibHienThi.setText(gt + Button7.getText());
        }
        
        
    }//GEN-LAST:event_Button7ActionPerformed

    
    
    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        String gt = this.ibHienThi.getText();
        if (gt.length() < 10)
        {
            if (gt.equals("0")){
                gt = "";
            }
            this.ibHienThi.setText(gt + Button1.getText());
        }
    }//GEN-LAST:event_Button1ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        String gt = this.ibHienThi.getText();
        if (gt.length() < 10)
        {
            if (gt.equals("0")){
                gt = "";
            }
            this.ibHienThi.setText(gt + Button2.getText());
        }
    }//GEN-LAST:event_Button2ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        String gt = this.ibHienThi.getText();
        if (gt.length() < 10)
        {
            if (gt.equals("0")){
                gt = "";
            }
            this.ibHienThi.setText(gt + Button3.getText());
        }
    }//GEN-LAST:event_Button3ActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
        String gt = this.ibHienThi.getText();
        if (gt.length() < 10)
        {
            if (gt.equals("0")){
                gt = "";
            }
            this.ibHienThi.setText(gt + Button4.getText());
        }
    }//GEN-LAST:event_Button4ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
        String gt = this.ibHienThi.getText();
        if (gt.length() < 10)
        {
            if (gt.equals("0")){
                gt = "";
            }
            this.ibHienThi.setText(gt + Button5.getText());
        }
    }//GEN-LAST:event_Button5ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        String gt = this.ibHienThi.getText();
        if (gt.length() < 10)
        {
            if (gt.equals("0")){
                gt = "";
            }
            this.ibHienThi.setText(gt + Button6.getText());
        }
    }//GEN-LAST:event_Button6ActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
        String gt = this.ibHienThi.getText();
        if (gt.length() < 10)
        {
            if (gt.equals("0")){
                gt = "";
            }
            this.ibHienThi.setText(gt + Button8.getText());
        }
    }//GEN-LAST:event_Button8ActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
        String gt = this.ibHienThi.getText();
        if (gt.length() < 10)
        {
            if (gt.equals("0")){
                gt = "";
            }
            this.ibHienThi.setText(gt + Button9.getText());
        }
    }//GEN-LAST:event_Button9ActionPerformed

    private String pheptoan = "";
    private double kp = 0;
    
    private void tinh (){
        if (this.pheptoan.equals("")) this.kp = Long.parseLong(ibHienThi.getText());
        else{
            if (this.pheptoan.equals("+")) this.kp += Double.parseDouble(ibHienThi.getText());
            if (this.pheptoan.equals("-")) this.kp -= Double.parseDouble(ibHienThi.getText());
            if (this.pheptoan.equals("X")) this.kp = this.kp * Double.parseDouble(ibHienThi.getText());
            if (this.pheptoan.equals("/")) this.kp = this.kp / Double.parseDouble(ibHienThi.getText());
        }
    }
    
    private void ButtonCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCongActionPerformed
        tinh();
        this.pheptoan = "+";
        ibHienThi.setText("0");
              
    }//GEN-LAST:event_ButtonCongActionPerformed

    private void ButtonTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTruActionPerformed
        tinh();       
        this.pheptoan = "-";
        ibHienThi.setText("0");
    }//GEN-LAST:event_ButtonTruActionPerformed

    private void ButtonNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNhanActionPerformed
        tinh();       
        this.pheptoan = "X";
        ibHienThi.setText("0");
    }//GEN-LAST:event_ButtonNhanActionPerformed

    private void ButtonChiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonChiaActionPerformed
        tinh();       
        this.pheptoan = "/";
        ibHienThi.setText("0");
    }//GEN-LAST:event_ButtonChiaActionPerformed

    private void ButtonBangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBangActionPerformed
        tinh();
        ibHienThi.setText(String.valueOf(this.kp));
        this.kp = 0;
    }//GEN-LAST:event_ButtonBangActionPerformed

    private void ButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCActionPerformed
        ibHienThi.setText("0");
        this.pheptoan = "";
    }//GEN-LAST:event_ButtonCActionPerformed

    private void Button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button0ActionPerformed
        String gt = this.ibHienThi.getText();
        if (gt.length() < 10)
        {
            if (gt.equals("0")){
                gt = "";
            }
            this.ibHienThi.setText(gt + Button0.getText());
        }
    }//GEN-LAST:event_Button0ActionPerformed
    
                                        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button0;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton ButtonBang;
    private javax.swing.JButton ButtonC;
    private javax.swing.JButton ButtonChia;
    private javax.swing.JButton ButtonCong;
    private javax.swing.JButton ButtonNhan;
    private javax.swing.JButton ButtonTru;
    private javax.swing.JLabel ibHienThi;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
