/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlkhambenh;

import com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tran Nguyen Quynh Anh
 */
public class CTKhamBenh extends javax.swing.JFrame {

    /**
     * Creates new form ThongTinBenhNhan
     */
    public CTKhamBenh() {
        initComponents();
        showTenBS();
        TableDichVu();
        DichvuBS();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        yeuCauKhamBox = new javax.swing.JTextField();
        ThemButton = new javax.swing.JButton();
        bsKham = new javax.swing.JComboBox<>();
        ngayKhambenh = new com.toedter.calendar.JDateChooser();
        tenBNBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tdichvu = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tdichvubs = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        ketluanBox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 248, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setText("KHÁM BỆNH");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tên bệnh nhân");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ngày khám");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Yêu cầu khám");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Bác sĩ khám");

        yeuCauKhamBox.setEditable(false);
        yeuCauKhamBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ThemButton.setBackground(new java.awt.Color(240, 255, 255));
        ThemButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ThemButton.setText("Thêm");
        ThemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemButtonActionPerformed(evt);
            }
        });

        bsKham.setBackground(new java.awt.Color(240, 255, 255));
        bsKham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bsKham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bsKhamMouseClicked(evt);
            }
        });

        ngayKhambenh.setBackground(new java.awt.Color(255, 255, 255));
        ngayKhambenh.setDoubleBuffered(false);
        ngayKhambenh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ngayKhambenh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ngayKhambenhKeyPressed(evt);
            }
        });

        tenBNBox.setBackground(new java.awt.Color(240, 255, 255));
        tenBNBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tenBNBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tenBNBoxMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Danh sách dịch vụ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Danh sách dịch vụ bác sĩ chọn");

        Tdichvu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tdichvu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên dịch vụ"
            }
        ));
        Tdichvu.setGridColor(new java.awt.Color(255, 255, 255));
        Tdichvu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TdichvuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tdichvu);

        Tdichvubs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tdichvubs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tdichvubs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên dịch vụ", "Số lượng"
            }
        ));
        jScrollPane2.setViewportView(Tdichvubs);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Kết luận");

        ketluanBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(255, 255, 255)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(82, 82, 82)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bsKham, 0, 173, Short.MAX_VALUE)
                                    .addComponent(tenBNBox, 0, 173, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ngayKhambenh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yeuCauKhamBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ketluanBox, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ThemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(286, 286, 286))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(bsKham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addComponent(ngayKhambenh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(yeuCauKhamBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tenBNBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel8))
                    .addComponent(ketluanBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(ThemButton)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Ham bat su kien Button Them 
     * @param evt 
     */
    private void ThemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemButtonActionPerformed
        DefaultTableModel model1 = (DefaultTableModel) Tdichvubs.getModel();
        // x la so luong dich vu
        int x = model1.getRowCount();
        //gia tien tung loai DV duoc chon
        int gia = 0;
        // tong tien tat ca DV duoc chon
        int tong = 0;
        // ma dv duoc chon
        String ma = null;
        // So luong cua tung loai dich vu
        int sldv = 0;

        for (int i = 0; i < x; i++) {
            try {
                String SQlQuery = "SELECT MADV, DONGIA FROM DICHVU WHERE TENDV = ? ";
                Connection con = null;
                con = sqlServerConnection.getMysSQLConnection();
                SQLServerPreparedStatement ps = (SQLServerPreparedStatement) con.prepareStatement(SQlQuery);
                ps.setString(1, (String) Tdichvubs.getValueAt(i, 0));
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    ma = rs.getString("MADV");
                    gia = rs.getInt("DONGIA");
                }
                
                if (!ma.isEmpty() && getMaKB() != 0) {
                    String str = "INSERT INTO THUPHI (MAKB, MADV, SOLUONG, THANHTIEN) VALUES(?, ?, ?, ?)";
                    SQLServerPreparedStatement ps1 = (SQLServerPreparedStatement) con.prepareStatement(str);
                    ps1.setInt(1, getMaKB());
                    ps1.setString(2, ma);
                    sldv = Integer.parseInt((String) Tdichvubs.getValueAt(i, 1));
                    ps1.setInt(3, sldv);
                    ps1.setInt(4, gia * sldv);
                    tong += gia * sldv;
                    int n = ps1.executeUpdate();
                    if (n > 0) {
                        JOptionPane.showMessageDialog(this, "Thêm thông tin thành công!");
                    } else {
                        JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi!");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi!");
                }     
            } catch (Exception e) {
                System.err.println(e);
            }      
        }
        
        if (tong > 0 && getMaKB() != 0) {
            String kl = ketluanBox.getText();
            String sql = "UPDATE KHAMBENH SET KETLUAN = ? , THANHTOAN = ? WHERE MAKB = ?";
            try {
                Connection con = null;
                con = sqlServerConnection.getMysSQLConnection();
                SQLServerPreparedStatement ps2 = (SQLServerPreparedStatement) con.prepareStatement(sql);
                ps2.setString(1, kl);
                ps2.setInt(2, 0);
                ps2.setInt(3, getMaKB());
                int m = ps2.executeUpdate();
                if (m > 0) {
                    JOptionPane.showMessageDialog(this, "Cập nhập thông tin thành công!");
                } else {
                    JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi!");
                }
            } catch (SQLException ex) {
                System.err.println(ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CTKhamBenh.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Xảy ra lỗi!");
        }

    }//GEN-LAST:event_ThemButtonActionPerformed

    private void TdichvuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TdichvuMouseClicked
        DefaultTableModel model = (DefaultTableModel) Tdichvu.getModel();
        int[] index = Tdichvu.getSelectedRows();
        Object[] row = new Object[2];
        DefaultTableModel model1 = (DefaultTableModel) Tdichvubs.getModel();
        for (int i = 0; i < index.length; i++) {
            String c = JOptionPane.showInputDialog(this, "Vui lòng nhập số lượng dịch vụ!");
            row[0] = model.getValueAt(i, 0);
            row[1] = c;
            model1.addRow(row);
            model.removeRow(i);
        }
    }//GEN-LAST:event_TdichvuMouseClicked

    private void ngayKhambenhKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ngayKhambenhKeyPressed

    }//GEN-LAST:event_ngayKhambenhKeyPressed

    /**
     * Ham lấy YEUCAUKHAM khi click vào tên bệnh nhân
     *
     * @param evt
     */
    private void tenBNBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tenBNBoxMouseClicked

        try {
            String sql = "SELECT YEUCAUKHAM FROM BENHNHAN BN JOIN "
                    + "                 (SELECT MABN, TENBS, YEUCAUKHAM "
                    + "                 FROM KHAMBENH KB JOIN BACSI BS ON KB.MABS = BS.MABS "
                    + "                 WHERE TENBS = ? AND NGAYKHAM = ? AND THANHTOAN IS NULL) A "
                    + "                 ON BN.MABN = A.MABN"
                    + "                 WHERE TENBN = ? ";

            Connection con = null;
            con = sqlServerConnection.getMysSQLConnection();

            SQLServerPreparedStatement ps = (SQLServerPreparedStatement) con.prepareStatement(sql);
            ps.setString(1, getTenBS());
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MMM/yy");
            String date = sdf.format(ngayKhambenh.getDate());
            ps.setString(2, date);
            String item = (String) tenBNBox.getSelectedItem();
            ps.setString(3, item);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                yeuCauKhamBox.setText(rs.getString("YEUCAUKHAM"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_tenBNBoxMouseClicked

    private void bsKhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsKhamMouseClicked
        ArrayList<String> tenbn = new ArrayList();
        tenBNBox.removeAllItems();
        tenbn.clear();

        int n = 0;
        try {
            String sql = "SELECT TENBN FROM BENHNHAN BN JOIN "
                    + "                 (SELECT MABN, TENBS, NGAYKHAM "
                    + "                 FROM KHAMBENH KB JOIN BACSI BS ON KB.MABS = BS.MABS "
                    + "                 WHERE TENBS = ? AND NGAYKHAM = ? AND THANHTOAN IS NULL) A "
                    + "                 ON BN.MABN = A.MABN";

            Connection con = null;
            con = sqlServerConnection.getMysSQLConnection();

            SQLServerPreparedStatement ps = (SQLServerPreparedStatement) con.prepareStatement(sql);
            ps.setString(1, getTenBS());
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MMM/yy");
            String date = sdf.format(ngayKhambenh.getDate());
            ps.setString(2, date);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                tenbn.add(rs.getString("TENBN"));
            }
            for (String string : tenbn) {
                tenBNBox.addItem(string);
                System.out.println(string);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_bsKhamMouseClicked

    /**
     * Ham lay ten BS
     *
     * @return
     */
    public String getTenBS() {
        return (String) bsKham.getSelectedItem();
    }

    /**
     * Ham dua ten BS tu csdl vao combobox
     */
    public void showTenBS() {
        ArrayList<String> bacsi = new ArrayList();
        try {
            Connection con = null;
            con = sqlServerConnection.getMysSQLConnection();
            String sql = "SELECT TENBS FROM BACSI";
            SQLServerPreparedStatement ps = (SQLServerPreparedStatement) con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                bacsi.add(rs.getString("TENBS"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        for (String string : bacsi) {
            bsKham.addItem(string);
        }
    }

    /**
     * Ham lay MABS tu ten BS da chon
     *
     * @return
     */
    public String getMaBS() {
        try {
            Connection con = null;
            con = sqlServerConnection.getMysSQLConnection();
            String str = "SELECT MABS FROM BACSI WHERE TENBS = ?";
            SQLServerPreparedStatement ps = (SQLServerPreparedStatement) con.prepareStatement(str);
            String item = (String) bsKham.getSelectedItem();
            ps.setString(1, item);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                return rs.getString("MABS");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        return null;
    }

    /**
     * Ham lay MAKB
     * @return 
     */
    public int getMaKB() {
        try {
            String sql = "SELECT MAKB FROM BENHNHAN BN JOIN "
                    + "                 (SELECT MABN, TENBS, NGAYKHAM, MAKB "
                    + "                 FROM KHAMBENH KB JOIN BACSI BS ON KB.MABS = BS.MABS "
                    + "                 WHERE TENBS = ? AND NGAYKHAM = ? AND THANHTOAN IS NULL) A "
                    + "                 ON BN.MABN = A.MABN";
            Connection con = null;
            con = sqlServerConnection.getMysSQLConnection();
            SQLServerPreparedStatement ps = (SQLServerPreparedStatement) con.prepareStatement(sql);

            ps.setString(1, getTenBS());
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MMM/yy");
            String date = sdf.format(ngayKhambenh.getDate());
            ps.setString(2, date);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                return rs.getInt("MAKB");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        return 0;
    }

    /**
     * Ham table Dich vu
     */
    public void TableDichVu() {
        DefaultTableModel model = (DefaultTableModel) Tdichvu.getModel();
        try {
            Connection con = null;
            con = sqlServerConnection.getMysSQLConnection();
            String row[] = new String[1];
            String SQLQuery = "SELECT TENDV FROM DICHVU";
            Statement stat = con.createStatement();
            ResultSet rs = stat.executeQuery(SQLQuery);
            while (rs.next()) {
                model.addRow(new String[]{rs.getString("TENDV")});
            }
            Tdichvu.setModel(model);
            Tdichvu.setVisible(true);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * Ham Table dich vu bac si chon
     */
    private void DichvuBS() {
        DefaultTableModel model1 = (DefaultTableModel) Tdichvubs.getModel();
        Tdichvubs.setModel(model1);
        Tdichvubs.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CTKhamBenh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CTKhamBenh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CTKhamBenh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CTKhamBenh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CTKhamBenh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tdichvu;
    private javax.swing.JTable Tdichvubs;
    private javax.swing.JButton ThemButton;
    private javax.swing.JComboBox<String> bsKham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField ketluanBox;
    private com.toedter.calendar.JDateChooser ngayKhambenh;
    private javax.swing.JComboBox<String> tenBNBox;
    private javax.swing.JTextField yeuCauKhamBox;
    // End of variables declaration//GEN-END:variables
}
