/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlkhambenh;

import com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement;
import java.awt.event.KeyEvent;

import java.sql.Connection;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Tran Nguyen Quynh Anh
 */
public class DatLichKham extends javax.swing.JFrame {

    /**
     * Creates new form ThongTinBenhNhan
     */
    public DatLichKham() {
        initComponents();
        showTenBS();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        maBNBox = new javax.swing.JTextField();
        tenBNBox = new javax.swing.JTextField();
        yeuCauKhamBox = new javax.swing.JTextField();
        DatLichKhamButton = new javax.swing.JButton();
        tenBS = new javax.swing.JComboBox<>();
        ngayKhambenh = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 248, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        jLabel1.setText("ĐẶT LỊCH KHÁM");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã bệnh nhân");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tên bệnh nhân");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ngày khám");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Yêu cầu khám");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Bác sĩ khám");

        maBNBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        maBNBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                maBNBoxKeyPressed(evt);
            }
        });

        tenBNBox.setEditable(false);
        tenBNBox.setBackground(new java.awt.Color(255, 255, 255));
        tenBNBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        yeuCauKhamBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        DatLichKhamButton.setBackground(new java.awt.Color(240, 255, 255));
        DatLichKhamButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DatLichKhamButton.setText("Đặt lịch khám");
        DatLichKhamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatLichKhamButtonActionPerformed(evt);
            }
        });

        tenBS.setBackground(new java.awt.Color(240, 255, 255));
        tenBS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tenBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenBSActionPerformed(evt);
            }
        });

        ngayKhambenh.setBackground(new java.awt.Color(255, 255, 255));
        ngayKhambenh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(maBNBox)
                    .addComponent(yeuCauKhamBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tenBNBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tenBS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ngayKhambenh, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(DatLichKhamButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(maBNBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tenBNBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ngayKhambenh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(yeuCauKhamBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenBS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(30, 30, 30)
                .addComponent(DatLichKhamButton)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tenBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenBSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenBSActionPerformed
    
    /**
     * Ham dua du lieu ten bac si vao combobox
     */
    public void showTenBS() {
        ArrayList<String> data = new ArrayList();

        try {
            Connection con = null;
            con = sqlServerConnection.getMysSQLConnection();
            String sql = "SELECT TENBS FROM BACSI";
            SQLServerPreparedStatement ps = (SQLServerPreparedStatement) con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                data.add(rs.getString("TENBS"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        for (String string : data) {
            tenBS.addItem(string);
        }
    }
    
    /**
     * Ham lay ma bac si tu ten bac si
     * @return 
     */
    public String getMaBS() {

        try {
            Connection con = null;
            con = sqlServerConnection.getMysSQLConnection();
            String str = "SELECT MABS FROM BACSI WHERE TENBS = ?";
            SQLServerPreparedStatement ps = (SQLServerPreparedStatement) con.prepareStatement(str);
            String item = (String) tenBS.getSelectedItem();
            ps.setString(1, item);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                return rs.getString("MABS");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        return null;
    }

    private void DatLichKhamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatLichKhamButtonActionPerformed
        String maBN = maBNBox.getText();
        String ycau = yeuCauKhamBox.getText();

        java.util.Date d = null;
        try {
            d = new SimpleDateFormat("yyyy-MM-dd").parse(LocalDate.now().toString());
        } catch (ParseException ex) {
            System.err.println(ex);
        }
        java.util.Date datetime = ngayKhambenh.getDate();
        //System.out.println(d.before(datetime));

        if (maBN.equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập mã bệnh nhân!");
        } else if (ycau.equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập yêu cầu khám!");
        } else if (datetime.before(d)) {
            JOptionPane.showMessageDialog(this, "Ngày khám bệnh phải lớn hơn hoặc bằng ngày hiện tại!");
        } else {
            String SQL = "INSERT INTO KHAMBENH (MABN, MABS, NGAYKHAM, YEUCAUKHAM) VALUES(?, ?, ?, ?)";
            try {
                Connection con = null;
                con = sqlServerConnection.getMysSQLConnection();
                SQLServerPreparedStatement ps = (SQLServerPreparedStatement) con.prepareStatement(SQL);

                ps.setString(1, maBN);
                ps.setString(2, getMaBS());
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MMM/yy");
                String date = sdf.format(ngayKhambenh.getDate());
                ps.setString(3, date);
                ps.setString(4, ycau);

                int rs = ps.executeUpdate();
                if (rs == 0) {
                    JOptionPane.showMessageDialog(this, "Đặt lich khám không thành công!");
                } else {
                    JOptionPane.showMessageDialog(this, "Đặt lịch khám thành công!");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }


    }//GEN-LAST:event_DatLichKhamButtonActionPerformed

    private void maBNBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maBNBoxKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String maBN = maBNBox.getText();
            String tenBN;
            int n = 0;
            try {

                String sql = "SELECT [TENBN] FROM [BENHNHAN] WHERE [MABN] =" + maBN;

                Connection con = null;
                con = sqlServerConnection.getMysSQLConnection();

                SQLServerPreparedStatement ps = (SQLServerPreparedStatement) con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();               

                while (rs.next()) {
                    tenBN = rs.getString("TENBN");
                    tenBNBox.setText(tenBN);
                    n = +1;
                }
                if (n == 0) {
                    JOptionPane.showMessageDialog(this, "Bệnh nhân chưa đăng ký!");
                }

            } catch (Exception e) {
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_maBNBoxKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatLichKham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatLichKham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatLichKham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatLichKham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatLichKham().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DatLichKhamButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField maBNBox;
    private com.toedter.calendar.JDateChooser ngayKhambenh;
    private javax.swing.JTextField tenBNBox;
    private javax.swing.JComboBox<String> tenBS;
    private javax.swing.JTextField yeuCauKhamBox;
    // End of variables declaration//GEN-END:variables
}
