/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlsanpham;

import com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tran Nguyen Quynh Anh
 */
public class SanPham extends javax.swing.JFrame {

    /**
     * Creates new form ThongTinBenhNhan
     */
    public SanPham() {
        initComponents();
        Table();
    }

    public void Table() {
        DefaultTableModel model = (DefaultTableModel) TableSP.getModel();
       
        try {
            Connection con = null;
            con = sqlServerConnectionSP.getMysSQLConnection();
            String row[] = new String[3];
            String SQLQuery = "SELECT * FROM SANPHAM";
            Statement stat = con.createStatement();
            ResultSet rs = stat.executeQuery(SQLQuery);
            while (rs.next()) {
                row[0] = rs.getString(1);
                row[1] = rs.getString(2);
                row[2] = rs.getString(3);
                model.addRow(row);
            }
        } catch (Exception e) {
            System.out.println(e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        maSPBox = new javax.swing.JTextField();
        tenSPBox = new javax.swing.JTextField();
        giaBox = new javax.swing.JTextField();
        ThemButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSP = new javax.swing.JTable();
        XoaButton = new javax.swing.JButton();
        SuaBottom = new javax.swing.JButton();
        ThoatButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 245, 238));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        jLabel1.setText("Sản phẩm");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã sản phẩm");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tên sản phẩm");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Giá");

        maSPBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tenSPBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        giaBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ThemButton.setBackground(new java.awt.Color(240, 255, 255));
        ThemButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ThemButton.setText("Thêm");
        ThemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemButtonActionPerformed(evt);
            }
        });

        TableSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TableSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableSP);

        XoaButton.setBackground(new java.awt.Color(240, 255, 255));
        XoaButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        XoaButton.setText("Xóa");
        XoaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaButtonActionPerformed(evt);
            }
        });

        SuaBottom.setBackground(new java.awt.Color(240, 255, 255));
        SuaBottom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SuaBottom.setText("Sửa");
        SuaBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaBottomActionPerformed(evt);
            }
        });

        ThoatButton.setBackground(new java.awt.Color(240, 255, 255));
        ThoatButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ThoatButton.setText("Thoát");
        ThoatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThoatButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(30, Short.MAX_VALUE)
                        .addComponent(ThemButton)
                        .addGap(25, 25, 25)
                        .addComponent(XoaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(SuaBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(ThoatButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(maSPBox, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                    .addComponent(giaBox, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tenSPBox, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(maSPBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenSPBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(giaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThemButton)
                    .addComponent(XoaButton)
                    .addComponent(SuaBottom)
                    .addComponent(ThoatButton))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SuaBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaBottomActionPerformed
        DefaultTableModel model = (DefaultTableModel) TableSP.getModel();
        int ret = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa dữ liệu?", "Sửa dữ liệu", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (ret == JOptionPane.YES_OPTION) {
            String strSQL = "UPDATE SANPHAM SET TENSP = ?, GIA = ? WHERE MASP = ?";
            try {
                Connection con = null;
                con = sqlServerConnectionSP.getMysSQLConnection();
                SQLServerPreparedStatement ps = (SQLServerPreparedStatement) con.prepareStatement(strSQL);
                ps.setString(1, tenSPBox.getText());
                ps.setInt(2, Integer.parseInt(giaBox.getText()));
                ps.setString(3, maSPBox.getText());
                ps.executeUpdate();
                int indexTB = TableSP.getSelectedRow();
                if (indexTB < model.getRowCount() && indexTB >= 0) {
                    model.setValueAt(tenSPBox.getText(), indexTB, 1);
                    model.setValueAt(giaBox.getText(), indexTB, 2);
                }
            } catch (Exception e) {
                System.err.println(e);
            }
        }

    }//GEN-LAST:event_SuaBottomActionPerformed

    private void ThemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) TableSP.getModel();
        if (maSPBox.getText().length() > 4) {
            JOptionPane.showMessageDialog(this, "Mã sản phẩm không nhiều hơn 4 ký tự!");
        } else if (tenSPBox.getText().length() > 20) {
            JOptionPane.showMessageDialog(this, "Tên sản phẩm không nhiều hơn 20 ký tự!");
        } else if (maSPBox.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập mã sản phẩm!");
        } else if (tenSPBox.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập tên sản phẩm!");
        } else if (giaBox.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập giá sản phẩm!");
        } else {
            try {
                String row[] = new String[3];
                row[0] = maSPBox.getText();
                row[1] = tenSPBox.getText();
                row[2] = giaBox.getText();
                model.addRow(row);
                
                String SQlQuery = "INSERT INTO [SANPHAM] VALUES (?,?,?)";
                Connection con = null;
                con = sqlServerConnectionSP.getMysSQLConnection();
                SQLServerPreparedStatement ps = (SQLServerPreparedStatement) con.prepareStatement(SQlQuery);
                ps.setString(1, maSPBox.getText());
                ps.setString(2, tenSPBox.getText());
                ps.setString(3, giaBox.getText());
                int n = ps.executeUpdate();

                if (n != 0) {
                    JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công!");
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm sản phẩm thất bại!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_ThemButtonActionPerformed

    private void XoaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) TableSP.getModel();
        int indexTB = TableSP.getSelectedRow();
        int ret = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa?", "Xóa dữ liệu", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (ret == JOptionPane.YES_OPTION) {
            if (indexTB < model.getRowCount() && indexTB >= 0) {
                model.removeRow(indexTB);
            }
            String str = "DELETE FROM SANPHAM WHERE MASP = ?";
            try {
                Connection con = null;
                con = sqlServerConnectionSP.getMysSQLConnection();
                SQLServerPreparedStatement ps = (SQLServerPreparedStatement) con.prepareStatement(str);
                ps.setString(1, maSPBox.getText());
                ps.executeUpdate();

            } catch (Exception e) {
                System.err.println(e);
            }
        }


    }//GEN-LAST:event_XoaButtonActionPerformed

    private void TableSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSPMouseClicked
        DefaultTableModel model = (DefaultTableModel) TableSP.getModel();
        int indexTB = TableSP.getSelectedRow();
        if (indexTB < model.getRowCount() && indexTB >= 0) {
            maSPBox.setText(model.getValueAt(indexTB, 0).toString());
            tenSPBox.setText(model.getValueAt(indexTB, 1).toString());
            giaBox.setText(model.getValueAt(indexTB, 2).toString());
        }
    }//GEN-LAST:event_TableSPMouseClicked

    private void ThoatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThoatButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ThoatButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SuaBottom;
    private javax.swing.JTable TableSP;
    private javax.swing.JButton ThemButton;
    private javax.swing.JButton ThoatButton;
    private javax.swing.JButton XoaButton;
    private javax.swing.JTextField giaBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField maSPBox;
    private javax.swing.JTextField tenSPBox;
    // End of variables declaration//GEN-END:variables
}
