/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ql_bongda;

import com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tran Nguyen Quynh Anh
 */
public class GiaiDau extends javax.swing.JFrame {

    /**
     * Creates new form TranDau
     */
    public GiaiDau() {
        initComponents();
        showTenGD();
        TableDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        GiaiDau = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbdsdoi = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbDsdoithamgia = new javax.swing.JTable();
        jButtonThem = new javax.swing.JButton();
        jButtonHuy = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tên giải đấu");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 104, 31));

        GiaiDau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(GiaiDau, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 170, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Danh sách đội");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 108, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Danh sách đội tham gia giải");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 207, -1));

        Tbdsdoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tbdsdoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã đội", "Tên đội"
            }
        ));
        Tbdsdoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbdsdoiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbdsdoi);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 296, 127));

        TbDsdoithamgia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TbDsdoithamgia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã đội", "Tên đội"
            }
        ));
        jScrollPane2.setViewportView(TbDsdoithamgia);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 330, 127));

        jButtonThem.setBackground(new java.awt.Color(255, 255, 255));
        jButtonThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonThem.setText("Thêm");
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 83, -1));

        jButtonHuy.setBackground(new java.awt.Color(255, 255, 255));
        jButtonHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonHuy.setText("Hủy");
        jButtonHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHuyActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 80, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ql_bongda/3 (3).jpg"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Ham load ten giai dau len combobox giai dau
     */
    public void showTenGD() {
        ArrayList<String> tengd = new ArrayList();
        try {
            Connection con = null;
            con = sqlServerConnection.getMysSQLConnection();
            String sql = "SELECT TENGIAI FROM GIAIDAU";
            SQLServerPreparedStatement ps = (SQLServerPreparedStatement) con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                tengd.add(rs.getString("TENGIAI"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        for (String str : tengd) {
            GiaiDau.addItem(str);
        }
    }
    
    /**
     * Ham load MAD, TENDOI tu csdl len table danh sach doi
     */
    public void TableDB() {
        DefaultTableModel model = (DefaultTableModel) Tbdsdoi.getModel();
        try {
            Connection con = null;
            con = sqlServerConnection.getMysSQLConnection();
            String row[] = new String[2];
            String SQLQuery = "SELECT MAD, TENDOI FROM DOIBONG";
            Statement stat = con.createStatement();
            ResultSet rs = stat.executeQuery(SQLQuery);
            while (rs.next()) {
                row[0] = rs.getString("MAD");
                row[1] = rs.getString("TENDOI");
                model.addRow(row);
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    /**
     * Ham lay ma giai dau tu ten giai dau
     * @return 
     */
    public String getMaGD() {
        try {
            Connection con = null;
            con = sqlServerConnection.getMysSQLConnection();
            String str = "SELECT MAG FROM GIAIDAU WHERE TENGIAI = ? ";
            SQLServerPreparedStatement ps = (SQLServerPreparedStatement) con.prepareStatement(str);
            String item = (String) GiaiDau.getSelectedItem();
            ps.setString(1, item);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                return rs.getString("MAG");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        return null;
    }
    
    


    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        DefaultTableModel model1 = (DefaultTableModel) TbDsdoithamgia.getModel();
        //So luong doi tham gia
        int x = model1.getRowCount();
        
        for(int i = 0; i < x ; i++){
            try {
                String SQlQuery = "INSERT INTO CT_GD (MAG, MAD) VALUES(?, ?)";
                Connection con = null;
                con = sqlServerConnection.getMysSQLConnection();
                SQLServerPreparedStatement ps = (SQLServerPreparedStatement) con.prepareStatement(SQlQuery);
                ps.setString(1, getMaGD());
                ps.setString(2, (String) model1.getValueAt(i, 0));           
                int rs = ps.executeUpdate();
                if (rs == 0) {
                    JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi!");
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm các đội vào giải đấu thành công!");
                }
                               
            } catch (Exception e) {
                System.err.println(e);
            }      
        }
    }//GEN-LAST:event_jButtonThemActionPerformed

    private void jButtonHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHuyActionPerformed
        DefaultTableModel model1 = (DefaultTableModel) TbDsdoithamgia.getModel();
        model1.setRowCount(0);

    }//GEN-LAST:event_jButtonHuyActionPerformed
    
    /**
     * Khi click vao đội trong ds doi thi doi se duoc load qua ds doi duoc chon
     * @param evt 
     */
    private void TbdsdoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbdsdoiMouseClicked
        DefaultTableModel model = (DefaultTableModel) Tbdsdoi.getModel();
        int i = Tbdsdoi.getSelectedRow();
        Object[] row = new String[2];
        DefaultTableModel model1 = (DefaultTableModel) TbDsdoithamgia.getModel();
        
        //Xét xem đội có được chọn chưa, nếu chọn rồi thì k thêm, nếu chưa được chọn thì thêm và table ds được chọn
        int x = 0;
        for (int j = 0; j < model1.getRowCount(); j++) {
            if (model1.getValueAt(j, 0).equals(model.getValueAt(i, 0))) {
                x += 1;
            }
        }
        if (x == 0) {
            row[0] = model.getValueAt(i, 0);
            row[1] = model.getValueAt(i, 1);
            model1.addRow(row);
        }
    }//GEN-LAST:event_TbdsdoiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaiDau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaiDau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaiDau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaiDau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaiDau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> GiaiDau;
    private javax.swing.JTable TbDsdoithamgia;
    private javax.swing.JTable Tbdsdoi;
    private javax.swing.JButton jButtonHuy;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
