/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ql_bongda;

import com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Tran Nguyen Quynh Anh
 */
public class TranDau extends javax.swing.JFrame {

    /**
     * Creates new form TranDau
     */
    public TranDau() {
        initComponents();
        showTenGD();
        showTenCN();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        GiaiDau = new javax.swing.JComboBox<>();
        jBtThem = new javax.swing.JButton();
        jBtHuy = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DoiKhach = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        NgayDaBox = new javax.swing.JTextField();
        DiaDiemBox = new javax.swing.JTextField();
        Doicn = new javax.swing.JComboBox<>();
        Doikhach = new javax.swing.JComboBox<>();
        TiSoBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tên giải đấu");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 104, 31));

        GiaiDau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        GiaiDau.setDoubleBuffered(true);
        GiaiDau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GiaiDauMouseClicked(evt);
            }
        });
        jPanel2.add(GiaiDau, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 190, -1));

        jBtThem.setBackground(new java.awt.Color(255, 255, 255));
        jBtThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtThem.setText("Thêm");
        jBtThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtThemActionPerformed(evt);
            }
        });
        jPanel2.add(jBtThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 83, -1));

        jBtHuy.setBackground(new java.awt.Color(255, 255, 255));
        jBtHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtHuy.setText("Hủy");
        jBtHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtHuyActionPerformed(evt);
            }
        });
        jPanel2.add(jBtHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 80, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ngày đá");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 108, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Địa điểm");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 70, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Chủ nhà");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        DoiKhach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DoiKhach.setForeground(new java.awt.Color(255, 255, 255));
        DoiKhach.setText("Đội khách");
        jPanel2.add(DoiKhach, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tỉ số");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        NgayDaBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(NgayDaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 140, -1));

        DiaDiemBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(DiaDiemBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 150, -1));

        Doicn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(Doicn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 140, -1));

        Doikhach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(Doikhach, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 150, -1));

        TiSoBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(TiSoBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 140, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ql_bongda/3 (3).jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Ham load tên giải đấu lên combo box
     */
    public void showTenGD() {
        ArrayList<String> tengd = new ArrayList();
        try {
            Connection con = null;
            con = sqlServerConnection.getMysSQLConnection();
            String sql = "SELECT TENGIAI FROM GIAIDAU";
            SQLServerPreparedStatement ps = (SQLServerPreparedStatement) con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                tengd.add(rs.getString("TENGIAI"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        for (String str : tengd) {
            GiaiDau.addItem(str);
        }
    }
    
    /**
     * Ham lay ma GD
     * @return 
     */
    public String getMaGD() {
        try {
            Connection con = null;
            con = sqlServerConnection.getMysSQLConnection();
            String str = "SELECT MAG FROM GIAIDAU WHERE TENGIAI = ?";
            SQLServerPreparedStatement ps = (SQLServerPreparedStatement) con.prepareStatement(str);
            String item = (String) GiaiDau.getSelectedItem();
            ps.setString(1, item);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                return rs.getString("MAG");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        return null;
    }

    
    public void showTenCN() {
        ArrayList<String> doicn = new ArrayList();
        ArrayList<String> doikhach = new ArrayList();
        try {
            Connection con = null;
            con = sqlServerConnection.getMysSQLConnection();
            String sql = "SELECT TENDOI FROM CT_GD INNER JOIN DOIBONG ON CT_GD.MAD = DOIBONG.MAD WHERE MAG = ?";
            SQLServerPreparedStatement ps = (SQLServerPreparedStatement) con.prepareStatement(sql);           
            ps.setString(1, getMaGD());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                doicn.add(rs.getString("TENDOI"));
                doikhach.add(rs.getString("TENDOI"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        for (String str : doicn) {
            Doicn.addItem(str);
            Doikhach.addItem(str);
        }
        
    }
    
    public String getMaDN() {
        try {
            Connection con = null;
            con = sqlServerConnection.getMysSQLConnection();
            String str = "SELECT MAD FROM DOIBONG WHERE TENDOI = ? ";
            SQLServerPreparedStatement ps = (SQLServerPreparedStatement) con.prepareStatement(str);
            String item = (String) Doicn.getSelectedItem();
            ps.setString(1, item);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                return rs.getString("MAD");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        return null;
    }
    
    public String getMaDK() {
        try {
            Connection con = null;
            con = sqlServerConnection.getMysSQLConnection();
            String str = "SELECT MAD FROM DOIBONG WHERE TENDOI = ? ";
            SQLServerPreparedStatement ps = (SQLServerPreparedStatement) con.prepareStatement(str);
            String item = (String) Doicn.getSelectedItem();
            ps.setString(1, item);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                return rs.getString("MAD");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        return null;
    }
    
    
    private void jBtThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtThemActionPerformed
        String ngayda = NgayDaBox.getText();
        String diadiem = DiaDiemBox.getText();
        String tiso = TiSoBox.getText();
        String cn = (String) Doicn.getSelectedItem();
        String khach = (String) Doikhach.getSelectedItem();
        
        if (cn.equals(khach)){
            JOptionPane.showMessageDialog(this, "Đội chủ nhà phải khác đội khách!");
        } else if (ngayda.equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập ngày đá!");
        } else if (diadiem.equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập địa điểm đá!");
        } else if (tiso.equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập tỉ số!");
        } else {
            try {
                String SQlQuery = "INSERT INTO TRANDAU (NGAYDA,DIADIEM,MAG,MADN,MADK,TISO) VALUES(?,?,?,?,?,?)";
                Connection con = null;
                con = sqlServerConnection.getMysSQLConnection();
                SQLServerPreparedStatement ps = (SQLServerPreparedStatement) con.prepareStatement(SQlQuery);
                ps.setString(1, ngayda);               
                ps.setString(2, diadiem);
                ps.setString(3, getMaGD());
                ps.setString(4, getMaDN());
                ps.setString(5, getMaDK());
                ps.setString(6, tiso);
                int rs = ps.executeUpdate();
                if (rs == 0) {
                    JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi!");
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm trận đấu thành công!");
                }
                               
            } catch (Exception e) {
                System.err.println(e);
            }      
            
        }
    }//GEN-LAST:event_jBtThemActionPerformed

    private void GiaiDauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GiaiDauMouseClicked
        ArrayList<String> doicn = new ArrayList();
        ArrayList<String> doikhach = new ArrayList();
        Doicn.removeAllItems();
        doicn.clear();
        Doikhach.removeAllItems();
        doikhach.clear();;
        try {
            Connection con = null;
            con = sqlServerConnection.getMysSQLConnection();
            String sql = "SELECT TENDOI FROM CT_GD INNER JOIN DOIBONG ON CT_GD.MAD = DOIBONG.MAD WHERE MAG = ?";
            SQLServerPreparedStatement ps = (SQLServerPreparedStatement) con.prepareStatement(sql);           
            ps.setString(1, getMaGD());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                doicn.add(rs.getString("TENDOI"));
                doikhach.add(rs.getString("TENDOI"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        for (String str : doicn) {
            Doicn.addItem(str);
            Doikhach.addItem(str);
        }

    }//GEN-LAST:event_GiaiDauMouseClicked

    private void jBtHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtHuyActionPerformed
        
    }//GEN-LAST:event_jBtHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TranDau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TranDau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TranDau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TranDau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TranDau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DiaDiemBox;
    private javax.swing.JLabel DoiKhach;
    private javax.swing.JComboBox<String> Doicn;
    private javax.swing.JComboBox<String> Doikhach;
    private javax.swing.JComboBox<String> GiaiDau;
    private javax.swing.JTextField NgayDaBox;
    private javax.swing.JTextField TiSoBox;
    private javax.swing.JButton jBtHuy;
    private javax.swing.JButton jBtThem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
